#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.tanzu.registry_secret_name
  namespace: #@ data.values.secrets.namespace
  labels:
    name: #@ data.values.tanzu.registry_secret_name
type: #@ data.values.tanzu.registry_secret_type
stringData:
  #@ tanzu_registry_creds = {"username": data.values.registry.username, "password": data.values.registry.password}
  .dockerconfigjson: #@ json.encode({"auths": {data.values.registry.server: tanzu_registry_creds}})
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ data.values.tanzu.registry_secret_name
  namespace: #@ data.values.secrets.namespace
spec:
  toNamespaces:
  - "*"
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: #@ data.values.tanzu.registry_secret_name
  namespace: #@ data.values.rabbitmq.package_install_namespace
spec:
  fromNamespace: #@ data.values.secrets.namespace
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: #@ data.values.tanzu.registry_secret_name
  namespace: #@ data.values.rabbitmq.cluster_namespace
spec:
  fromNamespace: #@ data.values.secrets.namespace
