#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: #@ data.values.rabbitmq.package_repo_name
  namespace: #@ data.values.rabbitmq.package_install_namespace
spec:
  fetch:
    imgpkgBundle:
      image: #@ data.values.registry.server + "/" + data.values.rabbitmq.package + ":" + data.values.rabbitmq.package_version
