#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: #@ data.values.rabbitmq.package_install_name
  namespace: #@ data.values.rabbitmq.package_install_namespace
spec:
  serviceAccountName: #@ data.values.rabbitmq.service_account_name
  packageRef:
    refName: #@ data.values.rabbitmq.package_ref_name
    namespace: #@ data.values.rabbitmq.package_install_namespace
    versionSelection:
      constraints: #@ data.values.rabbitmq.package_version